#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE USER ${UUID_GUIDE_ADMIN};
    ALTER USER ${UUID_GUIDE_ADMIN} WITH ENCRYPTED PASSWORD '${UUID_GUIDE_ADMIN_PASSWORD}';
    CREATE DATABASE ${UUID_GUIDE_DB} OWNER ${UUID_GUIDE_ADMIN};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${UUID_GUIDE_DB}" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    GRANT ALL PRIVILEGES ON DATABASE ${UUID_GUIDE_DB} TO ${UUID_GUIDE_ADMIN};
    ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO ${UUID_GUIDE_ADMIN};
    ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO ${UUID_GUIDE_ADMIN};
EOSQL

